import turtle 
t = turtle.Turtle()
t.color('white')
t.speed(0)
t.hideturtle()

for i in range (1,20):
    t.penup()
    t.goto(-670,-200)
    t.pendown()
    t.begin_fill()
    t.fillcolor('green')
    t.forward(1340)
    t.right(90)
    t.forward(140)
    t.right(90)
    t.forward(1340)
    t.right(90)
    t.forward(140)
    t.end_fill()

    t.begin_fill()
    t.fillcolor('light blue')
    t.forward(540)
    t.right(90)
    t.forward(1340)
    t.right(90)
    t.forward(540)
    t.right(90)
    t.forward(1340)
    t.end_fill()
    t.right(180)

    t.penup()
    t.goto(-470+(30*i),-150)
    t.begin_fill()
    t.fillcolor('red')
    t.pendown()
    t.forward(100)
    t.end_fill()
    t.penup()
    t.goto(-270+(30*i),-150)
    t.begin_fill()
    t.fillcolor('red')
    t.pendown()
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.right(45)
    t.forward(50)
    t.left(45)
    t.forward(230)
    t.left(45)
    t.forward(50)
    t.right(45)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.end_fill()
    t.penup()
    t.goto(-520+(30*i),-200)
    t.pendown()
    t.begin_fill()
    t.fillcolor('black')
    t.circle(50)
    t.end_fill()
    t.penup()
    t.goto(-320+(30*i),-200)
    t.pendown()
    t.begin_fill()
    t.fillcolor('black')
    t.circle(50)
    t.end_fill()

